In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
pre_post_df = pd.read_csv('bse_pre_post_data.csv')

In [3]:
pre_post_df.head()

,Unnamed: 0,uuid,Wave,Section,Row,Age,Gender,Tenure,Ovr_Sat,Team_Sat,Comm_Sat,Comm_Freq,Benefit_Sat,Benefit_Aware
0,0,ca962bfc,1,446,D,45-54,Male,11-20 season,3.0,7.0,7.0,Too few,NaN,NaN
1,1,b0b208b7,1,315,HH,45-54,Male,2-5 season,8.0,9.0,2.0,Too Many,NaN,NaN
2,2,e54d351c,1,183,J,25-34,Female,6-10 season,7.0,3.0,7.0,Too Many,NaN,Unaware
3,3,c62eeb63,1,143,M,55-64,Female,6-10 season,9.0,7.0,6.0,Too Many,8.0,Aware and have NOT used/received
4,4,1815ec0f,1,373,H,45-54,Female,11-15 season,8.0,5.0,7.0,Just Right,NaN,Unaware

In [4]:
pre_post_df['Tenure'].value_counts()

21+ seasons     848
2-5 season      692
6-10 season     531
11-15 season    283
11-20 season    272
1 season        214
16-20 season    213
Name: Tenure, dtype: int64

I noticed that there was a category from 11-20 which overlapped with other categories.  
I decided to get rid of any rows that had a tenure of '11-20 season' because I did not know if those belonged to the 11-15 category or 16-20 category.

In [5]:
#keep only rows where tenure is not equal to '11-20 season'
pre_post_df = pre_post_df[pre_post_df.Tenure != '11-20 season']

In [6]:
pre_post_df['Tenure'].value_counts()

21+ seasons     848
2-5 season      692
6-10 season     531
11-15 season    283
1 season        214
16-20 season    213
Name: Tenure, dtype: int64

I noticed that there were some phrases that had lower case letters and some that had uppercase letters. I wanted to replace the phrases with lower case letters so that they all matched.

In [18]:
#the following code is used to replace strings where the second word starts with a lower case letter
pre_post_df.loc['Comm_Freq'] = pre_post_df.loc['Comm_Freq'].str.replace('Too few', 'Too Few')
pre_post_df.loc['Comm_Freq'] = pre_post_df.loc['Comm_Freq'].str.replace('Too many', 'Too Many')
pre_post_df.loc['Comm_Freq'] = pre_post_df.loc['Comm_Freq'].str.replace('Just right', 'Just Right')

In [19]:
pre_post_df.head(20)

,Unnamed: 0,uuid,Wave,Section,Row,Age,Gender,Tenure,Ovr_Sat,Team_Sat,Comm_Sat,Comm_Freq,Benefit_Sat,Benefit_Aware
1,1.0,b0b208b7,1.0,315.0,HH,45-54,Male,2-5 season,8.0,9.0,2.0,Too Many,NaN,NaN
2,2.0,e54d351c,1.0,183.0,J,25-34,Female,6-10 season,7.0,3.0,7.0,Too Many,NaN,Unaware
3,3.0,c62eeb63,1.0,143.0,M,55-64,Female,6-10 season,9.0,7.0,6.0,Too Many,8.0,Aware and have NOT used/received
4,4.0,1815ec0f,1.0,373.0,H,45-54,Female,11-15 season,8.0,5.0,7.0,Just Right,NaN,Unaware
5,5.0,c4e9058c,1.0,114.0,F,45-54,Male,11-15 season,10.0,1.0,4.0,Too Many,NaN,Unaware
6,6.0,2dfe12e8,1.0,528.0,A,45-54,Female,2-5 season,6.0,7.0,6.0,Too Few,NaN,Unaware
7,7.0,f26bbe4b,1.0,93.0,P,65+,Male,21+ seasons,10.0,10.0,10.0,Just Right,7.0,Aware and have NOT used/received
8,8.0,ecf3dc76,1.0,293.0,KK,55-64,Male,6-10 season,9.0,7.0,7.0,Just Right,5.0,Aware and have NOT used/received
9,9.0,813ed71f,1.0,121.0,M,45-54,Male,2-5 season,9.0,10.0,10.0,Just Right,9.0,Aware and have used/received
10,10.0,5bb78133,1.0,85.0,Q,Prefer not to answer,Prefer not to answer,21+ seasons,4.0,2.0,3.0,Too Few,5.0,Aware and have NOT used/received
11,11.0,97325ddc,1.0,443.0,GG,55-64,Female,2-5 season,8.0,6.0,7.0,Just Right,NaN,Aware and have NOT used/received
12,12.0,b37baa11,1.0,45.0,D,55-64,Female,2-5 season,9.0,3.0,6.0,Too Few,8.0,Aware and have NOT used/received
14,14.0,cbd1cc53,1.0,28.0,D,55-64,Male,6-10 season,10.0,3.0,3.0,Too Few,6.0,Aware and have NOT used/received
16,16.0,e63d7718,1.0,318.0,R,25-34,Male,16-20 season,5.0,1.0,9.0,Just Right,NaN,Unaware
17,17.0,0cc29f25,1.0,122.0,LL,65+,Male,21+ seasons,8.0,8.0,8.0,Just Right,NaN,Aware and have NOT used/received
18,18.0,52bd7615,1.0,450.0,V,65+,Male,6-10 season,5.0,6.0,5.0,Too Few,NaN,Unaware
19,19.0,95ce63a4,1.0,104.0,Q,65+,Male,2-5 season,9.0,8.0,3.0,Too Few,NaN,Aware and have NOT used/received
20,20.0,dcb01035,1.0,99.0,K,35-44,Female,2-5 season,10.0,3.0,3.0,Just Right,6.0,Aware and have NOT used/received
21,21.0,c9e5f4bf,1.0,312.0,LL,35-44,Female,2-5 season,6.0,6.0,10.0,Just Right,NaN,Unaware
22,22.0,5ecb978d,1.0,489.0,C,65+,Male,21+ seasons,1.0,7.0,2.0,Too Few,NaN,Unaware

In [20]:
pre_post_df['Comm_Freq'].value_counts()

Just Right    1580
Too Few        689
Too Many       512
Name: Comm_Freq, dtype: int64

In [21]:
#use code to export to csv
#pre_post_df.to_csv('/users/veronicaventure/Documents/bse_pre_post_data.csv')